### ISSUE TITLE
GoAway are not handled properly by grpc client in reconnect.rs

### ISSUE THREAD

**Issue by DimanNe** [hyperium/tonic#2185]
### Version

v0.12.3

### Platform

Linux

### Description

Problem: even with retries implemented on the client side (manually) it seems, that grpc client uses same underlying TCP connection that is NOT accepting new http2 streams anymore.

How it happens?

Server decides to shut down, sends GoAway to client, `hyper-1.6.0/src/proto/h2/client.rs` interprets it as Ready(**Ok**):

```rust
    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        loop {
            match ready!(self.h2_tx.poll_ready(cx)) {
                Ok(()) => (),
                Err(err) => {
                    self.ping.ensure_not_timed_out()?;
                    return if err.reason() == Some(::h2::Reason::NO_ERROR) {
                        trace!("connection gracefully shutdown");
                        Poll::Ready(Ok(Dispatched::Shutdown))
```

and then tonic-0.12.3/src/transport/channel/service/reconnect.rs thinks that everything is fine, its state-machine does not initiate reconnect:

```
    fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        let mut state;

        if self.error.is_some() {
            return Poll::Ready(Ok(()));
        }

        loop {
            match self.state {
                State::Idle => {
                    trace!("poll_ready; idle");
                    match self.mk_service.poll_ready(cx) { ... }
                    let fut = self.mk_service.make_service(self.target.clone());
                    self.state = State::Connecting(fut);
                    continue;
                }
                State::Connecting(ref mut f) => {
                    trace!("poll_ready; connecting");
                    match Pin::new(f).poll(cx) { ... }
                }
                State::Connected(ref mut inner) => {
                    trace!("poll_ready; connected");

                    self.has_been_connected = true;

                    match inner.poll_ready(cx) {
                        Poll::Ready(Ok(())) => {
                            trace!("poll_ready; ready");
                            return Poll::Ready(Ok(()));
                        }
                        Poll::Pending => {
                            trace!("poll_ready; not ready");
                            return Poll::Pending;
                        }
                        Poll::Ready(Err(_)) => {
                            trace!("poll_ready; error");
                            state = State::Idle;
                        }
                    }
                }
            }

            self.state = state;
        }

        self.state = state;
        Poll::Ready(Ok(()))
    }
```

a consecutive call to `fn call(&mut self, request: Request) -> Self::Future {` returns a future that resolves into:

`Internal Error: Status { code: Internal, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", NO_ERROR, Remote) }))) }`

and then everything repeats.

**Comment by flokli** [comment]
There's no proper handling of GOAWAY with NO_ERROR in Tonic.
I ran into this when pointing Tonic to a gRPC TLS connection terminated by nginx, observing failures which didn't happen when pointing to the gRPC endpoint directly.

Turns out, load balancers like ELB or also just plain nginx [^1] send such a GOAWAY after a few thousand HTTP2 requests.

Whenever this happens, Tonic would need to reconnect and send uncommitted/in-flight requests / client-side stream chunks again, (for which there would need to be some buffering).

I really think this should be dealt with transparently in Tonic, considering it happens so frequently.

--
[^1]: https://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests

**Comment by flokli** [comment]
There's also the double-GOAWAY, which we can handle to move traffic over to a new connection /before/ we have a failed request (if we get lucky), see https://github.com/grpc/grpc/issues/24237#issue-708437340.

**Comment by flokli** [comment]
@edef1c, @arianvp and I spent some time on this (mostly @edef1c really), and there's now a branch for hyper and tonic implementing the necessary changes:

 - https://github.com/arianvp/hyper/tree/push-ktssyytnyrru
 - https://github.com/edef1c/tonic/tree/push-rosuyzxnysvw

In your downstream project, you can pull in the changes by adding the following to your `Cargo.toml` (make sure to be on tonic 0.14.x and hyper 1.9.x before):

```toml
[patch.crates-io]
hyper = { git = "https://github.com/arianvp/hyper.git", branch = "push-ktssyytnyrru" }
tonic = { git = "https://github.com/edef1c/tonic.git", branch = "push-rosuyzxnysvw" }
tonic-health = { git = "https://github.com/edef1c/tonic.git", branch = "push-rosuyzxnysvw" }
tonic-reflection = { git = "https://github.com/edef1c/tonic.git", branch = "push-rosuyzxnysvw" }
tonic-prost = { git = "https://github.com/edef1c/tonic.git", branch = "push-rosuyzxnysvw" }
tonic-prost-build = { git = "https://github.com/edef1c/tonic.git", branch = "push-rosuyzxnysvw" }
```

We can confirm this fixes the issues both in [buck2](https://github.com/facebook/buck2) and [Snix](https://snix.dev), when talking to a gRPC endpoint exposed via nginx.

We'll try to upstream these in the next days, it would be great if others can test it on their end and report back here.
